### ISSUE TITLE
xwm leaves zombie processes

### ISSUE THREAD

**Issue by vainiovano** [mcpcpc/xwm#11]
xwm doesn't `wait` the `exit` statuses of the processes that it creates. When a process created by xwm `exit`s, it's left as a zombie until it's are reaped by init when xwm is closed.

**Comment by mcpcpc** [comment]
https://github.com/mcpcpc/xwm/pull/12 should now address this and properly reap zombie processes.  Messing around with alternative options at the moment (e.g. double fork), so I will most likely hold off merging for a day or two.  

**edit**: I will most likely proceed with the "double fork" method since the `signal.h` library is arguably not preferred (as it contains implementation-defined and undefined behavior).
